# mostly from https://github.com/marketplace/actions/build-and-push-docker-images
name: Build and push container

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Extract tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: BACKY2_VERSION=${{ env.RELEASE_VERSION }}
          push: true
          tags: ghcr.io/djeebus/backy2:${{ env.RELEASE_VERSION }}
